// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://moohcttaexbfxrbrpwtn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1vb2hjdHRhZXhiZnhyYnJwd3RuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4OTQ1MzksImV4cCI6MjA2NzQ3MDUzOX0.0gWZ4RVySGtumY9tV_m_VOT3npe1QDAdURU67Ma7mfE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});